[tool.poetry]
name = "splinator"
version = "0.1.1"
description = "Python library for fitting linear-spine based logistic regression for calibration."
authors = ["Jiarui Xu <jiarui.xu@affirm.com>"]
license = 'BSD-3-Clause'
keywords = ["calibration", "logistic", "spline", "regression"]
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7.1"
scipy = "^1.6.0"
scikit-learn = "^1.0.0"
numpy = "^1.19.0"
pandas = "^1.3.0"
cvxopt = "^1.3.0"
jax = "^0.3.25"
jaxopt = "0.7.0"


[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
matplotlib = "^3.5.3"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
